<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="CSharpFunctionalExtensions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\Shared.Application\Shared.Application.csproj" />
    <ProjectReference Include="..\Trips.Domain\Trips.Domain.csproj" />
  </ItemGroup>

</Project>
