<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Catalog\Catalog.Infrastructure.Sql\Catalog.Infrastructure.Sql.csproj" />
    <ProjectReference Include="..\..\Shared\Shared.Tests\Shared.Tests.csproj" />
  </ItemGroup>

</Project>
