<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Trips.Infrastructure.Sql.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Trips.Domain\Trips.Domain.csproj" />
  </ItemGroup>

</Project>
