<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
